CREATE DATABASE IF NOT EXISTS mrt_library CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mrt_library;

CREATE TABLE admins (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(60) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL);
INSERT INTO admins (username,password) VALUES ('admin', '$2y$10$AkvOirRCdyO0jlahWXSkyuMB5u8DUDEEvXkFqV4T14jNuU8huKyHW');

CREATE TABLE categories (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ebooks (id INT AUTO_INCREMENT PRIMARY KEY, category_id INT NOT NULL, title VARCHAR(255) NOT NULL, keywords VARCHAR(500), pdf_file VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE CASCADE);
CREATE TABLE members (id INT AUTO_INCREMENT PRIMARY KEY, membership_id VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, guardian_name VARCHAR(150) NOT NULL, mobile VARCHAR(20) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, email VARCHAR(150), address TEXT NOT NULL, aadhar_no VARCHAR(30) NOT NULL, duration ENUM('Yearly','Half Yearly','Quarterly','Monthly','Daily') NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, payment_id VARCHAR(150) NOT NULL, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE reading_requests (id INT AUTO_INCREMENT PRIMARY KEY, member_id INT NOT NULL, ebook_id INT NOT NULL, status ENUM('Pending','Approved','Rejected','Expired') DEFAULT 'Pending', requested_at DATETIME DEFAULT CURRENT_TIMESTAMP, approved_at DATETIME NULL, expires_at DATETIME NULL, FOREIGN KEY(member_id) REFERENCES members(id) ON DELETE CASCADE, FOREIGN KEY(ebook_id) REFERENCES ebooks(id) ON DELETE CASCADE);
CREATE TABLE print_requests (id INT AUTO_INCREMENT PRIMARY KEY, member_id INT NOT NULL, ebook_id INT NOT NULL, pages VARCHAR(100) NOT NULL, status ENUM('Pending','Completed') DEFAULT 'Pending', requested_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(member_id) REFERENCES members(id) ON DELETE CASCADE, FOREIGN KEY(ebook_id) REFERENCES ebooks(id) ON DELETE CASCADE);
CREATE TABLE physical_books (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, book_code VARCHAR(100) NOT NULL UNIQUE, price DECIMAL(10,2) NOT NULL, author VARCHAR(150), publisher VARCHAR(150), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE lendings (id INT AUTO_INCREMENT PRIMARY KEY, member_id INT NOT NULL, physical_book_id INT NOT NULL, lent_at DATETIME NOT NULL, due_date DATE NOT NULL, transaction_id VARCHAR(150) NOT NULL, returned_at DATETIME NULL, fine_amount DECIMAL(10,2) DEFAULT 0.00, fine_status ENUM('None', 'Outstanding', 'Paid', 'Waived') DEFAULT 'None', fine_payment_id VARCHAR(150) NULL, FOREIGN KEY(member_id) REFERENCES members(id), FOREIGN KEY(physical_book_id) REFERENCES physical_books(id));
